name: Terraform Apply infra

on:
  workflow_run:
    workflows: ["Terraform Plan infra"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    #  THIS is the approval gate
    environment: production

    steps:
      - name: Checkout same commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          run-id: ${{ github.event.workflow_run.id }}
          path: infra

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply tfplan
